[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://YOUR_API_DOMAIN/api"
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = "your_walletconnect_project_id"
  NEXT_PUBLIC_CHAIN_ID = "84532"
  NEXT_PUBLIC_RPC_URL = "https://sepolia.base.org"
  NEXT_PUBLIC_PAYMASTER_ADDRESS = "your_paymaster_address"
  NEXT_PUBLIC_USDC_ADDRESS = "your_usdc_address"
  NEXT_PUBLIC_COINBASE_APP_NAME = "PayKit Demo"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_API_DOMAIN/api/:splat"
  status = 200
  force = true
