name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile=false
      - name: Typecheck
        run: pnpm typecheck || true
      - name: Build
        run: pnpm build || true
      - name: Test
        run: pnpm test || true
      - name: Foundry (skip if not installed)
        run: |
          if command -v forge >/dev/null 2>&1; then
            pnpm contracts:build && pnpm contracts:test;
          else
            echo "forge not installed, skipping";
          fi 